version: '3.7'
services:
  compile:
    # Paths for bind mounts must be absolute and are therefor system-specific.
    # Configure paths in an .env file (or as system environment variables).
    env_file: .env
    build:
      context: .
      args:
        # Allow end-user to override userid/groupid during build
        # Default arguments must be provided here
        userid: ${USERID:-1000}       # Set to USER to inherit from your system
        groupid: ${GROUPID:-1000}     # Set to GROUPS to inherit from your system?
    volumes:
      # Mount the source code and build output in the container.
      # This allows for easy changes since data persists on the host.
      - type: bind
        source: ${SRC_PATH_HOST:?Must set environment variable SRC_PATH_HOST}
        target: ${SRC_PATH_TARGET:?Must set environment variable SRC_PATH_TARGET}
      - type: bind
        source: ${BUILD_PATH_HOST:?Must set environment variable BUILD_PATH_HOST}
        target: ${BUILD_PATH_TARGET:?Must set environment variable BUILD_PATH_TARGET}

    tty: true
    stdin_open: true
