remote_theme: KevinWMatthews/minima
title: c/hello_world
author: Kevin W Matthews
author_url: https://www.kevinwmatthews.com
description:
  Hello World in C.
  Configured with CMake.
  Run with Docker.
header_pages:
  - system-tools.md
  - docker.md
github_username: KevinWMatthews
linkedin_username: KevinWMatthews
